/*
  Licensed under the Apache License, Version 2.0
    http://www.apache.org/licenses/LICENSE-2.0.html

  AUTOGENERATED BY H2O at 2016-11-16T14:22:16.688+05:30
  3.10.0.8
  
  Standalone prediction code with sample test data for GBMModel named GBMModel

  How to download, compile and execute:
      mkdir tmpdir
      cd tmpdir
      curl http://127.0.0.1:54321/3/h2o-genmodel.jar > h2o-genmodel.jar
      curl http://127.0.0.1:54321/3/Models.java/GBMModel > GBMModel.java
      javac -cp h2o-genmodel.jar -J-Xmx2g -J-XX:MaxPermSize=128m GBMModel.java

     (Note:  Try java argument -XX:+PrintCompilation to show runtime JIT compiler behavior.)
*/
import java.util.Map;
import hex.genmodel.GenModel;
import hex.genmodel.annotations.ModelPojo;

@ModelPojo(name="GBMModel", algorithm="gbm")
public class GBMModel extends GenModel {
  public hex.ModelCategory getModelCategory() { return hex.ModelCategory.Multinomial; }

  public boolean isSupervised() { return true; }
  public int nfeatures() { return 4; }
  public int nclasses() { return 8; }

  // Names of columns used by model.
  public static final String[] NAMES = NamesHolder_GBMModel.VALUES;
  // Number of output classes included in training data response column.
  public static final int NCLASSES = 8;

  // Column domains. The last array contains domain of response column.
  public static final String[][] DOMAINS = new String[][] {
    /* mbvp */ null,
    /* mffdbvp */ null,
    /* mgsr */ null,
    /* mffdgsr */ null,
    /* emotion */ GBMModel_ColInfo_4.VALUES
  };
  // Prior class distribution
  public static final double[] PRIOR_CLASS_DISTRIB = {0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.125};
  // Class distribution used for model building
  public static final double[] MODEL_CLASS_DISTRIB = {0.125,0.125,0.125,0.125,0.125,0.125,0.125,0.125};

  public GBMModel() { super(NAMES,DOMAINS); }
  public String getUUID() { return Long.toString(9049598100021122384L); }

  // Pass in data in a double[], pre-aligned to the Model's requirements.
  // Jam predictions into the preds[] array; preds[0] is reserved for the
  // main prediction (class for classifiers or value for regression),
  // and remaining columns hold a probability distribution for classifiers.
  public final double[] score0( double[] data, double[] preds ) {
    java.util.Arrays.fill(preds,0);
    GBMModel_Forest_0.score0(data,preds);
    GBMModel_Forest_1.score0(data,preds);
    GBMModel_Forest_2.score0(data,preds);
    GBMModel_Forest_3.score0(data,preds);
    GBMModel_Forest_4.score0(data,preds);
    GBMModel_Forest_5.score0(data,preds);
    GBMModel_Forest_6.score0(data,preds);
    GBMModel_Forest_7.score0(data,preds);
    GBMModel_Forest_8.score0(data,preds);
    GBMModel_Forest_9.score0(data,preds);
    hex.genmodel.GenModel.GBM_rescale(preds);
    preds[0] = hex.genmodel.GenModel.getPrediction(preds, PRIOR_CLASS_DISTRIB, data, 0.5);
    return preds;
  }
}
// The class representing training column names
class NamesHolder_GBMModel implements java.io.Serializable {
  public static final String[] VALUES = new String[4];
  static {
    NamesHolder_GBMModel_0.fill(VALUES);
  }
  static final class NamesHolder_GBMModel_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "mbvp";
      sa[1] = "mffdbvp";
      sa[2] = "mgsr";
      sa[3] = "mffdgsr";
    }
  }
}
// The class representing column emotion
class GBMModel_ColInfo_4 implements java.io.Serializable {
  public static final String[] VALUES = new String[8];
  static {
    GBMModel_ColInfo_4_0.fill(VALUES);
  }
  static final class GBMModel_ColInfo_4_0 implements java.io.Serializable {
    static final void fill(String[] sa) {
      sa[0] = "anger";
      sa[1] = "grief";
      sa[2] = "hate";
      sa[3] = "joy";
      sa[4] = "no emotion";
      sa[5] = "platonic";
      sa[6] = "reverence";
      sa[7] = "romantic";
    }
  }
}

class GBMModel_Forest_0 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_0_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_0_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_0_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_0_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_0_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_0_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_0_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_0_class_7.score0(fdata);
  }
}
class GBMModel_Tree_0_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6211232f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6709.9126f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.7526009E-8f ? 
                -0.1f : 
                -0.027272727f) : 
            0.14f) : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.6533f ? 
            0.04117647f : 
            0.43333334f));
    return pred;
  } // constant pool size = 18B, number of visited nodes = 4, static init size = 0B
}

class GBMModel_Tree_0_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[2 /* mgsr */] <0.1965008f ? 
        0.19090909f : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6500807f ? 
             (data[1 /* mffdbvp */] <-9.289831E-5f ? 
                -0.1f : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.46776342f ? 
                     (data[0 /* mbvp */] <6695.158f ? 
                        -0.03846154f : 
                        0.1f) : 
                     (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <1.4189325E-4f ? 
                        -0.1f : 
                        -0.02f))) : 
             (data[0 /* mbvp */] <6701.1147f ? 
                0.16666667f : 
                -0.033333335f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_0_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.3861645E-9f ? 
        -0.1f : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.5368645E-8f ? 
             (data[0 /* mbvp */] <6696.946f ? 
                0.25f : 
                 (data[1 /* mffdbvp */] <-3.9623897E-5f ? 
                    -0.02f : 
                    0.22f)) : 
             (data[2 /* mgsr */] <0.49586022f ? 
                0.06f : 
                -0.03846154f)));
    return pred;
  } // constant pool size = 22B, number of visited nodes = 5, static init size = 0B
}

class GBMModel_Tree_0_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (data[0 /* mbvp */] <6693.4844f ? 
            0.21111111f : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.8274677E-9f ? 
                 (data[0 /* mbvp */] <6696.2827f ? 
                    0.06f : 
                     (data[2 /* mgsr */] <0.30624658f ? 
                        -0.02f : 
                        -0.1f)) : 
                0.13529412f)) : 
        -0.1f);
    return pred;
  } // constant pool size = 22B, number of visited nodes = 5, static init size = 0B
}

class GBMModel_Tree_0_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6707.309f ? 
             (data[1 /* mffdbvp */] <-1.5108237E-5f ? 
                 (data[2 /* mgsr */] <0.391957f ? 
                    0.045454547f : 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6700.2007f ? 
                        -0.1f : 
                        -0.02f)) : 
                -0.1f) : 
            0.0882353f) : 
        0.3923077f);
    return pred;
  } // constant pool size = 22B, number of visited nodes = 5, static init size = 0B
}

class GBMModel_Tree_0_class_5 {
  static final double score0(double[] data) {
    double pred =      (data[1 /* mffdbvp */] <-2.6969393E-4f ? 
        0.20769231f : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.1147f ? 
             (data[2 /* mgsr */] <0.41422418f ? 
                0.15263158f : 
                 (data[3 /* mffdgsr */] <-5.722051E-9f ? 
                    0.06f : 
                     (data[0 /* mbvp */] <6691.998f ? 
                        0.06f : 
                        -0.1f))) : 
            -0.1f));
    return pred;
  } // constant pool size = 22B, number of visited nodes = 5, static init size = 0B
}

class GBMModel_Tree_0_class_6 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.2899237E-8f ? 
         (data[2 /* mgsr */] <0.25216872f ? 
            0.06f : 
             (data[3 /* mffdgsr */] <-5.8000516E-9f ? 
                0.02631579f : 
                -0.1f)) : 
         (data[3 /* mffdgsr */] <1.751315E-8f ? 
            0.35714287f : 
            -0.052941177f));
    return pred;
  } // constant pool size = 18B, number of visited nodes = 4, static init size = 0B
}

class GBMModel_Tree_0_class_7 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.74207E-9f ? 
         (data[3 /* mffdgsr */] <-5.4574287E-9f ? 
            -0.1f : 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6698.601f ? 
                 (data[3 /* mffdgsr */] <2.7545133E-10f ? 
                    0.33636364f : 
                    0.1f) : 
                0.033333335f)) : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6059692f ? 
             (data[0 /* mbvp */] <6693.3916f ? 
                -0.02f : 
                -0.1f) : 
            0.023076924f));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}


class GBMModel_Forest_1 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_1_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_1_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_1_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_1_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_1_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_1_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_1_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_1_class_7.score0(fdata);
  }
}
class GBMModel_Tree_1_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6211232f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6709.9126f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.7526009E-8f ? 
                 (data[2 /* mgsr */] <0.23096928f ? 
                    -0.0981898f : 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6695.885f ? 
                        -0.098611854f : 
                        -0.09894453f)) : 
                -0.02473865f) : 
            0.112552635f) : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.6533f ? 
            0.03847403f : 
            0.2796532f));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_1_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[2 /* mgsr */] <0.1965008f ? 
        0.1523013f : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6500807f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.1689158E-8f ? 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6698.9604f ? 
                     (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <3.937617E-5f ? 
                        -0.09912101f : 
                        0.016291037f) : 
                     (data[2 /* mgsr */] <0.5127803f ? 
                        0.124518335f : 
                        -0.021435712f)) : 
                 (data[1 /* mffdbvp */] <-9.6451644E-5f ? 
                    -0.09845999f : 
                    -0.09992882f)) : 
             (data[2 /* mgsr */] <0.7047375f ? 
                0.15069829f : 
                -0.033587787f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_1_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.3861645E-9f ? 
         (data[2 /* mgsr */] <0.18722281f ? 
            -0.09820774f : 
             (data[3 /* mffdgsr */] <-6.5223036E-9f ? 
                -0.09885396f : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6702.1924f ? 
                     (data[2 /* mgsr */] <0.45938835f ? 
                        -0.09849782f : 
                        -0.09881803f) : 
                    -0.09840867f))) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.5368645E-8f ? 
             (data[3 /* mffdgsr */] <8.100538E-9f ? 
                0.03441803f : 
                 (data[0 /* mbvp */] <6697.798f ? 
                    0.2779779f : 
                    0.057964105f)) : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <2.0005176E-8f ? 
                -0.039584212f : 
                0.06925406f)));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_1_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (data[0 /* mbvp */] <6693.4844f ? 
            0.15933385f : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.8274677E-9f ? 
                 (data[0 /* mbvp */] <6696.2827f ? 
                    0.051107846f : 
                     (data[2 /* mgsr */] <0.30624658f ? 
                        -0.016373891f : 
                        -0.09878287f)) : 
                0.10931363f)) : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6505035f ? 
             (data[2 /* mgsr */] <0.4430941f ? 
                -0.09841624f : 
                 (data[0 /* mbvp */] <6696.3906f ? 
                    -0.09862189f : 
                    -0.09898403f)) : 
            -0.09787341f));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_1_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6707.309f ? 
             (data[1 /* mffdbvp */] <-1.5108237E-5f ? 
                 (data[2 /* mgsr */] <0.391957f ? 
                    0.044614665f : 
                     (data[1 /* mffdbvp */] <-1.6824983E-4f ? 
                        -0.014032473f : 
                        -0.09916533f)) : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6566888f ? 
                     (data[2 /* mgsr */] <0.36578536f ? 
                        -0.09848372f : 
                        -0.09877928f) : 
                    -0.09839586f)) : 
            0.07504494f) : 
        0.26110733f);
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_1_class_5 {
  static final double score0(double[] data) {
    double pred =      (data[1 /* mffdbvp */] <-2.6969393E-4f ? 
        0.16409108f : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.1147f ? 
             (data[2 /* mgsr */] <0.41422418f ? 
                0.12537032f : 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <5.064464E-5f ? 
                     (data[1 /* mffdbvp */] <-7.7987606E-5f ? 
                        -0.09956518f : 
                        0.08049814f) : 
                    -0.0996224f)) : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.61833984f ? 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5080056f ? 
                    -0.0986528f : 
                    -0.09890761f) : 
                -0.09826598f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_1_class_6 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.2899237E-8f ? 
         (data[2 /* mgsr */] <0.25216872f ? 
            0.055071518f : 
             (data[3 /* mffdgsr */] <-5.8000516E-9f ? 
                0.021627326f : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6702.1924f ? 
                     (data[0 /* mbvp */] <6693.4844f ? 
                        -0.09852158f : 
                        -0.098880135f) : 
                    -0.09841894f))) : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.2944f ? 
            0.24214037f : 
            -0.10110812f));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_1_class_7 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.0407898E-8f ? 
         (data[3 /* mffdgsr */] <-5.469385E-9f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-9.7087955E-9f ? 
                -0.09890437f : 
                -0.09861061f) : 
             (data[3 /* mffdgsr */] <2.7451733E-10f ? 
                0.16848707f : 
                 (data[1 /* mffdbvp */] <-1.21185614E-4f ? 
                    0.18824665f : 
                     (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <8.6172666E-5f ? 
                        -0.099897414f : 
                        0.058691356f)))) : 
         (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <5.5610013E-5f ? 
             (data[2 /* mgsr */] <0.46762088f ? 
                -0.09857429f : 
                -0.09936917f) : 
            -0.013092748f));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}


class GBMModel_Forest_2 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_2_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_2_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_2_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_2_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_2_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_2_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_2_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_2_class_7.score0(fdata);
  }
}
class GBMModel_Tree_2_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6211232f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6709.9126f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.7526009E-8f ? 
                 (data[2 /* mgsr */] <0.23096928f ? 
                    -0.09673782f : 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6695.885f ? 
                        -0.09741377f : 
                        -0.09795248f)) : 
                -0.022281447f) : 
            0.09185256f) : 
         (data[3 /* mffdgsr */] <1.0119898E-9f ? 
            0.28447503f : 
            0.030539034f));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_2_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[2 /* mgsr */] <0.1965008f ? 
        0.12644593f : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6500807f ? 
             (data[1 /* mffdbvp */] <-9.289831E-5f ? 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6698.9604f ? 
                    -0.09725036f : 
                    -0.09844707f) : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.46776342f ? 
                     (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.43831986f ? 
                        -0.013362761f : 
                        0.108840175f) : 
                     (data[3 /* mffdgsr */] <2.2572824E-9f ? 
                        -0.016534192f : 
                        -0.09850891f))) : 
             (data[2 /* mgsr */] <0.7047375f ? 
                0.12753877f : 
                -0.030132359f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_2_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.3861645E-9f ? 
         (data[2 /* mgsr */] <0.18722281f ? 
            -0.09673011f : 
             (data[3 /* mffdgsr */] <-6.5223036E-9f ? 
                -0.097864166f : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6702.1924f ? 
                     (data[2 /* mgsr */] <0.45938835f ? 
                        -0.097282924f : 
                        -0.09776773f) : 
                    -0.09692305f))) : 
         (data[3 /* mffdgsr */] <1.001807E-8f ? 
            0.14694566f : 
             (data[2 /* mgsr */] <0.45201457f ? 
                0.1393029f : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6699.389f ? 
                    0.051324457f : 
                    -0.10053406f))));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_2_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (data[0 /* mbvp */] <6693.4844f ? 
            0.12507994f : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.8274677E-9f ? 
                 (data[1 /* mffdbvp */] <-5.7539186E-5f ? 
                    0.051793516f : 
                     (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <2.016874E-4f ? 
                        -0.099038415f : 
                        -0.013296235f)) : 
                0.09071961f)) : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6505035f ? 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6700.9443f ? 
                -0.09723793f : 
                -0.09785427f) : 
            -0.09624799f));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_2_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6707.309f ? 
             (data[1 /* mffdbvp */] <-1.5108237E-5f ? 
                 (data[2 /* mgsr */] <0.391957f ? 
                    0.043512512f : 
                     (data[1 /* mffdbvp */] <-1.6824983E-4f ? 
                        -0.011234087f : 
                        -0.098174915f)) : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6393699f ? 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6697.951f ? 
                        -0.09741807f : 
                        -0.097958066f) : 
                    -0.09715801f)) : 
            0.06411556f) : 
        0.20012932f);
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_2_class_5 {
  static final double score0(double[] data) {
    double pred =      (data[1 /* mffdbvp */] <-2.6969393E-4f ? 
        0.13971636f : 
         (data[3 /* mffdgsr */] <-1.0519352E-8f ? 
            0.12318827f : 
             (data[1 /* mffdbvp */] <-2.5554564E-5f ? 
                 (data[2 /* mgsr */] <0.41917244f ? 
                    -0.10103688f : 
                     (data[2 /* mgsr */] <0.5393431f ? 
                        -0.098599456f : 
                        -0.09752774f)) : 
                 (data[1 /* mffdbvp */] <2.6066456E-5f ? 
                    0.1307796f : 
                     (data[2 /* mgsr */] <0.42164657f ? 
                        0.012916256f : 
                        -0.09801092f)))));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_2_class_6 {
  static final double score0(double[] data) {
    double pred =      (data[0 /* mbvp */] <6696.267f ? 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.2614512E-8f ? 
             (data[1 /* mffdbvp */] <-9.713986E-6f ? 
                0.09885969f : 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.5487353E-9f ? 
                    -0.099497065f : 
                    -0.0061985217f)) : 
            0.23138045f) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.774196E-9f ? 
             (data[2 /* mgsr */] <0.25711697f ? 
                -0.10086025f : 
                 (data[3 /* mffdgsr */] <-4.5641912E-9f ? 
                    -0.100416176f : 
                    -0.09736445f)) : 
             (data[2 /* mgsr */] <0.41422418f ? 
                0.12935199f : 
                 (data[3 /* mffdgsr */] <1.3353429E-8f ? 
                    -0.014112214f : 
                    -0.10130742f))));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_2_class_7 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.74207E-9f ? 
         (data[3 /* mffdgsr */] <-5.4574287E-9f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-9.753036E-9f ? 
                -0.09790331f : 
                -0.097492985f) : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5292712f ? 
                 (data[0 /* mbvp */] <6695.3696f ? 
                    0.2851885f : 
                    0.05030957f) : 
                -0.0037910442f)) : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6059692f ? 
             (data[0 /* mbvp */] <6693.3916f ? 
                -0.0114598395f : 
                 (data[3 /* mffdgsr */] <1.2936888E-8f ? 
                    -0.09897443f : 
                    -0.09763374f)) : 
            0.036400035f));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}


class GBMModel_Forest_3 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_3_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_3_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_3_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_3_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_3_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_3_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_3_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_3_class_7.score0(fdata);
  }
}
class GBMModel_Tree_3_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6211232f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6709.9126f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.7526009E-8f ? 
                 (data[1 /* mffdbvp */] <-2.3227946E-4f ? 
                    -0.09569079f : 
                     (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.4569244f ? 
                        -0.09637199f : 
                        -0.09701285f)) : 
                -0.019795436f) : 
            0.077278f) : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.6533f ? 
            0.020134961f : 
            0.18445443f));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_3_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[2 /* mgsr */] <0.1965008f ? 
        0.10278167f : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6500807f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.1689158E-8f ? 
                 (data[0 /* mbvp */] <6696.088f ? 
                     (data[2 /* mgsr */] <0.42739576f ? 
                        -0.003461369f : 
                        -0.09886803f) : 
                     (data[0 /* mbvp */] <6701.0254f ? 
                        0.114651494f : 
                        -0.046733133f)) : 
                 (data[0 /* mbvp */] <6698.9604f ? 
                    -0.09621002f : 
                    -0.098367f)) : 
             (data[0 /* mbvp */] <6701.1147f ? 
                0.11317785f : 
                -0.029046021f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_3_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.3861645E-9f ? 
         (data[1 /* mffdbvp */] <-1.6184861E-4f ? 
            -0.0956185f : 
             (data[1 /* mffdbvp */] <-4.7919024E-5f ? 
                -0.09704852f : 
                 (data[3 /* mffdgsr */] <-6.1289773E-9f ? 
                    -0.09672099f : 
                     (data[2 /* mgsr */] <0.3820605f ? 
                        -0.0959762f : 
                        -0.09636541f)))) : 
         (data[3 /* mffdgsr */] <1.001807E-8f ? 
            0.11968726f : 
             (data[2 /* mgsr */] <0.45201457f ? 
                0.11506991f : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6699.389f ? 
                    0.046480145f : 
                    -0.09953386f))));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_3_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6706.322f ? 
             (data[2 /* mgsr */] <0.40061647f ? 
                 (data[2 /* mgsr */] <0.23574378f ? 
                    -0.013216646f : 
                    -0.044134196f) : 
                 (data[0 /* mbvp */] <6693.4897f ? 
                    0.18459228f : 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.8738808E-9f ? 
                        -0.05039021f : 
                        0.19028094f))) : 
            -0.09941634f) : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.63442165f ? 
             (data[0 /* mbvp */] <6696.3906f ? 
                -0.09599481f : 
                 (data[2 /* mgsr */] <0.43955553f ? 
                    -0.0962092f : 
                    -0.09730122f)) : 
            -0.095225774f));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_3_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6707.309f ? 
             (data[1 /* mffdbvp */] <-1.5108237E-5f ? 
                 (data[2 /* mgsr */] <0.391957f ? 
                    0.040937413f : 
                     (data[1 /* mffdbvp */] <-1.6824983E-4f ? 
                        -0.008105766f : 
                        -0.097237706f)) : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6393699f ? 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6697.951f ? 
                        -0.096399575f : 
                        -0.09709327f) : 
                    -0.09604788f)) : 
            0.05546977f) : 
        0.1612208f);
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_3_class_5 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.2047475E-9f ? 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <2.5375182E-9f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-3.3416334E-9f ? 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.54660547f ? 
                    0.13543573f : 
                    -0.038313802f) : 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <6.0893562E-5f ? 
                    -0.10183681f : 
                    -0.012137707f)) : 
            0.19260845f) : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.55030125f ? 
             (data[3 /* mffdgsr */] <1.2321919E-8f ? 
                -0.10108952f : 
                -0.09873547f) : 
             (data[3 /* mffdgsr */] <1.3515777E-8f ? 
                0.06219304f : 
                -0.09756445f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_3_class_6 {
  static final double score0(double[] data) {
    double pred =      (data[0 /* mbvp */] <6696.267f ? 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.2614512E-8f ? 
             (data[3 /* mffdgsr */] <-5.293192E-9f ? 
                0.08746937f : 
                 (data[2 /* mgsr */] <0.44850633f ? 
                    -0.0026900205f : 
                    -0.09739287f)) : 
            0.18286097f) : 
         (data[2 /* mgsr */] <0.36968985f ? 
            0.020816592f : 
             (data[1 /* mffdbvp */] <-1.176497E-4f ? 
                -0.047819328f : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6110868f ? 
                     (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.51848257f ? 
                        -0.098097496f : 
                        -0.09924386f) : 
                    -0.09702298f))));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_3_class_7 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.0407898E-8f ? 
         (data[3 /* mffdgsr */] <-5.469385E-9f ? 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5775167f ? 
                -0.09703197f : 
                -0.09616193f) : 
             (data[0 /* mbvp */] <6694.292f ? 
                0.14731313f : 
                 (data[3 /* mffdgsr */] <3.788817E-9f ? 
                     (data[1 /* mffdbvp */] <5.5610013E-5f ? 
                        0.001227466f : 
                        0.13217105f) : 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.734616E-9f ? 
                        -0.04426572f : 
                        -0.0041633956f)))) : 
         (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <5.5610013E-5f ? 
             (data[3 /* mffdgsr */] <1.6431668E-8f ? 
                -0.097771384f : 
                -0.09655894f) : 
            -0.0070485007f));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}


class GBMModel_Forest_4 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_4_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_4_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_4_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_4_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_4_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_4_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_4_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_4_class_7.score0(fdata);
  }
}
class GBMModel_Tree_4_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6211232f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6709.9126f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.7526009E-8f ? 
                 (data[1 /* mffdbvp */] <-1.6759954E-4f ? 
                    -0.09488309f : 
                     (data[1 /* mffdbvp */] <-6.572869E-5f ? 
                        -0.09649221f : 
                        -0.09555677f)) : 
                -0.01813367f) : 
            0.0644772f) : 
         (data[3 /* mffdgsr */] <1.0119898E-9f ? 
            0.19239284f : 
            0.017054113f));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_4_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[2 /* mgsr */] <0.1965008f ? 
        0.08682859f : 
         (data[3 /* mffdgsr */] <-6.9602955E-9f ? 
            -0.10091692f : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6499314f ? 
                 (data[3 /* mffdgsr */] <2.6725597E-10f ? 
                    0.06997173f : 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6700.397f ? 
                        -0.014926012f : 
                        -0.0981786f)) : 
                 (data[2 /* mgsr */] <0.70487505f ? 
                    0.14375208f : 
                    -0.006476068f))));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_4_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.3861645E-9f ? 
         (data[3 /* mffdgsr */] <-6.092428E-9f ? 
            -0.09590447f : 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6702.1924f ? 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.4587585f ? 
                    -0.09502148f : 
                    -0.09587718f) : 
                -0.094802685f)) : 
         (data[3 /* mffdgsr */] <1.001807E-8f ? 
            0.102154985f : 
             (data[2 /* mgsr */] <0.45201457f ? 
                0.093569316f : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6699.389f ? 
                    0.04123062f : 
                    -0.098551154f))));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_4_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (data[1 /* mffdbvp */] <-2.5201438E-4f ? 
            -0.10258183f : 
             (data[1 /* mffdbvp */] <-9.200052E-5f ? 
                0.20319535f : 
                 (data[0 /* mbvp */] <6693.933f ? 
                    0.10276893f : 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.1820294E-10f ? 
                        -0.09764879f : 
                        0.04780404f)))) : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.63442165f ? 
             (data[0 /* mbvp */] <6696.3906f ? 
                -0.09513441f : 
                 (data[2 /* mgsr */] <0.43955553f ? 
                    -0.09537647f : 
                    -0.09662277f)) : 
            -0.09429284f));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_4_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6707.309f ? 
             (data[1 /* mffdbvp */] <-1.5108237E-5f ? 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.560768E-9f ? 
                     (data[2 /* mgsr */] <0.42807314f ? 
                        0.053425714f : 
                        -0.031981308f) : 
                    -0.097804874f) : 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.63204E-9f ? 
                     (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <1.4783404E-4f ? 
                        -0.09521676f : 
                        -0.09560913f) : 
                    -0.096029475f)) : 
            0.047959108f) : 
        0.13335499f);
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_4_class_5 {
  static final double score0(double[] data) {
    double pred =      (data[1 /* mffdbvp */] <-2.6969393E-4f ? 
        0.11324447f : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.1147f ? 
             (data[2 /* mgsr */] <0.41422418f ? 
                0.09900411f : 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <5.064464E-5f ? 
                     (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <-2.4195937E-5f ? 
                        -0.055466384f : 
                        0.096126206f) : 
                    -0.09746283f)) : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <9.553724E-9f ? 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.59800136f ? 
                    -0.098243594f : 
                    -0.09721411f) : 
                -0.09652268f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_4_class_6 {
  static final double score0(double[] data) {
    double pred =      (data[0 /* mbvp */] <6696.267f ? 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.2614512E-8f ? 
             (data[1 /* mffdbvp */] <-9.713986E-6f ? 
                0.085623816f : 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.5487353E-9f ? 
                    -0.09882788f : 
                    0.001073197f)) : 
            0.14878456f) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.774196E-9f ? 
             (data[2 /* mgsr */] <0.25711697f ? 
                -0.099601924f : 
                 (data[3 /* mffdgsr */] <-4.5641912E-9f ? 
                    -0.09813652f : 
                    -0.0954793f)) : 
             (data[2 /* mgsr */] <0.41422418f ? 
                0.10909461f : 
                 (data[3 /* mffdgsr */] <1.3353429E-8f ? 
                    -0.009747606f : 
                    -0.09939388f))));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_4_class_7 {
  static final double score0(double[] data) {
    double pred =      (data[0 /* mbvp */] <6689.8936f ? 
        0.11665092f : 
         (data[2 /* mgsr */] <0.18722281f ? 
            0.09220349f : 
             (data[1 /* mffdbvp */] <-1.3532926E-4f ? 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <9.956038E-9f ? 
                    0.13330613f : 
                    -0.09619328f) : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.60172415f ? 
                     (data[0 /* mbvp */] <6694.239f ? 
                        -0.043426234f : 
                        -0.099390514f) : 
                     (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <7.883904E-5f ? 
                        -0.0986991f : 
                        0.0776819f)))));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class GBMModel_Forest_5 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_5_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_5_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_5_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_5_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_5_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_5_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_5_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_5_class_7.score0(fdata);
  }
}
class GBMModel_Tree_5_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6211232f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6709.9126f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.7526009E-8f ? 
                 (data[1 /* mffdbvp */] <-1.6759954E-4f ? 
                    -0.09399051f : 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6699.2017f ? 
                        -0.09469825f : 
                        -0.095649034f)) : 
                -0.01581124f) : 
            0.05421667f) : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.6533f ? 
            0.008621288f : 
            0.13967662f));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_5_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[0 /* mbvp */] <6696.1772f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6693.1943f ? 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6691.378f ? 
                -0.09662691f : 
                0.05287369f) : 
            -0.0992719f) : 
         (data[0 /* mbvp */] <6701.108f ? 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6698.47f ? 
                0.024263453f : 
                0.1805576f) : 
             (data[3 /* mffdgsr */] <2.185975E-9f ? 
                0.114127494f : 
                 (data[2 /* mgsr */] <0.43787456f ? 
                    -0.101698734f : 
                     (data[1 /* mffdbvp */] <-3.1857664E-5f ? 
                        -0.09590893f : 
                        -0.09808529f)))));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_5_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.3861645E-9f ? 
         (data[3 /* mffdgsr */] <-6.092428E-9f ? 
            -0.095164746f : 
             (data[1 /* mffdbvp */] <-1.3939352E-4f ? 
                -0.0939015f : 
                 (data[2 /* mgsr */] <0.36968985f ? 
                    -0.09420034f : 
                     (data[2 /* mgsr */] <0.6124638f ? 
                        -0.09507764f : 
                        -0.094263755f)))) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.5368645E-8f ? 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5033461f ? 
                0.022481123f : 
                0.12631561f) : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <2.0005176E-8f ? 
                -0.048133254f : 
                0.07306417f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_5_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6706.322f ? 
             (data[2 /* mgsr */] <0.40061647f ? 
                 (data[2 /* mgsr */] <0.23574378f ? 
                    -0.009946999f : 
                    -0.04441168f) : 
                 (data[0 /* mbvp */] <6693.4897f ? 
                    0.13336073f : 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.8738808E-9f ? 
                        -0.047036707f : 
                        0.14006516f))) : 
            -0.09788736f) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.9277037E-8f ? 
             (data[0 /* mbvp */] <6696.3906f ? 
                -0.09430883f : 
                 (data[3 /* mffdgsr */] <1.2914024E-8f ? 
                    -0.09522427f : 
                    -0.095800355f)) : 
            -0.09350275f));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_5_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6707.309f ? 
             (data[0 /* mbvp */] <6690.4556f ? 
                0.013204595f : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6704.0527f ? 
                     (data[3 /* mffdgsr */] <-2.4377695E-9f ? 
                        -0.03773168f : 
                        -0.09621061f) : 
                    -0.0123449825f)) : 
            0.04075194f) : 
        0.11488175f);
    return pred;
  } // constant pool size = 22B, number of visited nodes = 5, static init size = 0B
}

class GBMModel_Tree_5_class_5 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.2047475E-9f ? 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <2.5375182E-9f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-3.3416334E-9f ? 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.54660547f ? 
                    0.10509086f : 
                    -0.033834726f) : 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <6.0893562E-5f ? 
                    -0.101603836f : 
                    -0.008023462f)) : 
            0.15220955f) : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.55030125f ? 
             (data[3 /* mffdgsr */] <1.2321919E-8f ? 
                -0.10030036f : 
                -0.09712397f) : 
             (data[2 /* mgsr */] <0.6156954f ? 
                0.05742335f : 
                -0.098045975f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_5_class_6 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0]) || data[0 /* mbvp */] <6703.0f ? 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.247215E-8f ? 
             (data[2 /* mgsr */] <0.25247797f ? 
                0.14730068f : 
                 (data[3 /* mffdgsr */] <-5.607704E-9f ? 
                    0.05508491f : 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.345925E-9f ? 
                        -0.09593393f : 
                        -0.09815713f))) : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.7504183E-8f ? 
                0.15915424f : 
                -0.028613277f)) : 
         (data[2 /* mgsr */] <0.47545886f ? 
            -0.10112042f : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.61458516f ? 
                -0.09686345f : 
                -0.0941733f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_5_class_7 {
  static final double score0(double[] data) {
    double pred =      (data[0 /* mbvp */] <6689.8936f ? 
        0.10201703f : 
         (data[2 /* mgsr */] <0.18722281f ? 
            0.07881591f : 
             (data[1 /* mffdbvp */] <-1.3532926E-4f ? 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <9.956038E-9f ? 
                    0.11510742f : 
                    -0.09538117f) : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.60172415f ? 
                     (data[1 /* mffdbvp */] <-3.4681755E-6f ? 
                        -0.057732772f : 
                        -0.09944933f) : 
                     (data[0 /* mbvp */] <6697.491f ? 
                        -0.09987988f : 
                        0.06384935f)))));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class GBMModel_Forest_6 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_6_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_6_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_6_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_6_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_6_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_6_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_6_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_6_class_7.score0(fdata);
  }
}
class GBMModel_Tree_6_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6211232f ? 
         (data[3 /* mffdgsr */] <-8.099193E-9f ? 
            0.09119874f : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.7516278E-8f ? 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6705.783f ? 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6699.179f ? 
                        -0.09375128f : 
                        -0.0947339f) : 
                    -0.10650312f) : 
                0.02297656f)) : 
         (data[3 /* mffdgsr */] <1.0119898E-9f ? 
            0.1455015f : 
            0.009482452f));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_6_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[1 /* mffdbvp */] <-5.223532E-5f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.1147f ? 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6696.5f ? 
                -0.022182645f : 
                0.17443824f) : 
            -0.04051153f) : 
         (data[1 /* mffdbvp */] <3.781132E-5f ? 
             (data[3 /* mffdgsr */] <3.4809853E-9f ? 
                -0.10433306f : 
                -0.0977163f) : 
             (data[1 /* mffdbvp */] <1.2552348E-4f ? 
                0.10976421f : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6703.0337f ? 
                    -0.102352165f : 
                    0.0589781f))));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_6_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.3861645E-9f ? 
         (data[1 /* mffdbvp */] <-1.6184861E-4f ? 
            -0.09313975f : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.65297765f ? 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.4631462f ? 
                     (data[3 /* mffdgsr */] <-2.1154738E-9f ? 
                        -0.09396469f : 
                        -0.09366066f) : 
                    -0.09468196f) : 
                -0.09356386f)) : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.6533f ? 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5033461f ? 
                 (data[2 /* mgsr */] <0.44143745f ? 
                    0.052208457f : 
                    -0.059071206f) : 
                0.14684641f) : 
             (data[2 /* mgsr */] <0.54291415f ? 
                0.052471474f : 
                -0.10228642f)));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_6_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (data[1 /* mffdbvp */] <-2.5201438E-4f ? 
            -0.10092471f : 
             (data[1 /* mffdbvp */] <-9.200052E-5f ? 
                0.16064373f : 
                 (data[2 /* mgsr */] <0.4661809f ? 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.1820294E-10f ? 
                        -0.1074184f : 
                        0.026500467f) : 
                     (data[2 /* mgsr */] <0.60303116f ? 
                        0.1398259f : 
                        0.01803204f)))) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.9277037E-8f ? 
             (data[0 /* mbvp */] <6696.3906f ? 
                -0.09364454f : 
                 (data[3 /* mffdgsr */] <1.2914024E-8f ? 
                    -0.0945562f : 
                    -0.095146425f)) : 
            -0.09276253f));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_6_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5645275f ? 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6703.449f ? 
                 (data[2 /* mgsr */] <0.37438822f ? 
                     (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.25151992f ? 
                        -0.09648857f : 
                        0.102659315f) : 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6695.032f ? 
                        -0.094296396f : 
                        -0.09559983f)) : 
                0.09325236f) : 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6704.7056f ? 
                 (data[1 /* mffdbvp */] <-2.2400694E-5f ? 
                    -0.096093476f : 
                    -0.094413385f) : 
                -0.10137792f)) : 
        0.09910603f);
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_6_class_5 {
  static final double score0(double[] data) {
    double pred =      (data[1 /* mffdbvp */] <-2.6969393E-4f ? 
        0.09628986f : 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.1147f ? 
             (data[2 /* mgsr */] <0.41422418f ? 
                0.08325979f : 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <5.064464E-5f ? 
                     (data[1 /* mffdbvp */] <-7.7987606E-5f ? 
                        -0.096159056f : 
                        0.060235914f) : 
                    -0.096654445f)) : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <9.553724E-9f ? 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.0256369E-9f ? 
                    -0.096797965f : 
                    -0.098081715f) : 
                -0.09553719f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_6_class_6 {
  static final double score0(double[] data) {
    double pred =      (data[0 /* mbvp */] <6695.8184f ? 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.2614512E-8f ? 
             (data[3 /* mffdgsr */] <-5.293192E-9f ? 
                0.08264229f : 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <3.456098E-5f ? 
                    -0.095959134f : 
                    0.0105802035f)) : 
            0.1268934f) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.774196E-9f ? 
             (data[2 /* mgsr */] <0.25711697f ? 
                -0.09852372f : 
                 (data[3 /* mffdgsr */] <-5.5219616E-9f ? 
                    -0.09756533f : 
                    -0.093971714f)) : 
             (data[1 /* mffdbvp */] <-1.2825744E-4f ? 
                -0.10591298f : 
                 (data[0 /* mbvp */] <6701.3643f ? 
                    0.12616238f : 
                    -0.02736572f))));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_6_class_7 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <8.124538E-5f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6697.8833f ? 
             (data[2 /* mgsr */] <0.448862f ? 
                0.08615229f : 
                 (data[1 /* mffdbvp */] <-9.730166E-5f ? 
                    0.029187255f : 
                    -0.09809128f)) : 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6708.8003f ? 
                 (data[3 /* mffdgsr */] <5.2793347E-9f ? 
                    -0.103852436f : 
                     (data[3 /* mffdgsr */] <1.1692209E-8f ? 
                        -0.09648963f : 
                        -0.094838895f)) : 
                0.010593959f)) : 
         (data[1 /* mffdbvp */] <2.0060143E-4f ? 
            0.13536638f : 
            -0.01836075f));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}


class GBMModel_Forest_7 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_7_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_7_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_7_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_7_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_7_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_7_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_7_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_7_class_7.score0(fdata);
  }
}
class GBMModel_Tree_7_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.6533f ? 
         (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <1.7936695E-4f ? 
             (data[3 /* mffdgsr */] <-5.982477E-9f ? 
                -0.020445568f : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.61846465f ? 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.992602E-9f ? 
                        -0.09296339f : 
                        -0.09435718f) : 
                    -0.10405678f)) : 
            0.08133355f) : 
         (data[2 /* mgsr */] <0.44082105f ? 
            -0.10223654f : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6149681f ? 
                0.074508816f : 
                0.11317178f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_7_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[2 /* mgsr */] <0.1965008f ? 
        0.06458709f : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.698894f ? 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6700.576f ? 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6696.8135f ? 
                     (data[2 /* mgsr */] <0.44180253f ? 
                        0.07004804f : 
                        -0.09857362f) : 
                    0.09185508f) : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6709.291f ? 
                     (data[1 /* mffdbvp */] <-1.5108237E-5f ? 
                        -0.09535832f : 
                        -0.1020621f) : 
                    -6.4867584E-4f)) : 
            0.07896024f));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_7_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.3861645E-9f ? 
         (data[1 /* mffdbvp */] <-1.6184861E-4f ? 
            -0.09255721f : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.65297765f ? 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.45901945f ? 
                    -0.09320414f : 
                    -0.09394816f) : 
                -0.09297081f)) : 
         (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <1.12184614E-4f ? 
             (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <1.8040944E-5f ? 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <-8.505128E-5f ? 
                     (data[1 /* mffdbvp */] <-2.111393E-4f ? 
                        0.0940082f : 
                        -0.056236025f) : 
                    0.10763719f) : 
                -0.063140795f) : 
            0.09503466f));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_7_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6706.322f ? 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.4661809f ? 
                 (data[1 /* mffdbvp */] <-6.8539804E-5f ? 
                    0.055976965f : 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-1.9114557E-10f ? 
                        -0.10343365f : 
                        0.024321606f)) : 
                 (data[1 /* mffdbvp */] <-4.5011955E-5f ? 
                    0.005966923f : 
                    0.12178154f)) : 
            -0.09765212f) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.9277037E-8f ? 
             (data[0 /* mbvp */] <6696.3906f ? 
                -0.09303061f : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.53266746f ? 
                    -0.09431144f : 
                    -0.09389512f)) : 
            -0.092091806f));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_7_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (data[2 /* mgsr */] <0.29855862f ? 
             (data[2 /* mgsr */] <0.18687367f ? 
                -0.09827302f : 
                -0.102400005f) : 
             (data[2 /* mgsr */] <0.38293272f ? 
                0.23984955f : 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <2.8898023E-4f ? 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6704.1587f ? 
                        -0.068750605f : 
                        -0.10330758f) : 
                    0.038597297f))) : 
        0.08921377f);
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_7_class_5 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.055026E-8f ? 
         (data[1 /* mffdbvp */] <-2.6969393E-4f ? 
            0.102331616f : 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.1147f ? 
                 (data[1 /* mffdbvp */] <-8.0540616E-5f ? 
                    -0.09842118f : 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6696.2754f ? 
                        0.025692396f : 
                        0.17754534f)) : 
                 (data[0 /* mbvp */] <6705.6597f ? 
                    -0.09715495f : 
                    -0.09568743f))) : 
         (data[3 /* mffdgsr */] <1.3471467E-8f ? 
            -0.09885529f : 
             (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <-3.9504677E-5f ? 
                -0.094623476f : 
                -0.0960548f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_7_class_6 {
  static final double score0(double[] data) {
    double pred =      (data[0 /* mbvp */] <6695.8184f ? 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.2614512E-8f ? 
             (data[1 /* mffdbvp */] <-9.810755E-6f ? 
                0.0814173f : 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <9.396766E-10f ? 
                    -0.09878626f : 
                    0.013554876f)) : 
            0.11105068f) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.774196E-9f ? 
             (data[2 /* mgsr */] <0.25711697f ? 
                -0.097567186f : 
                 (data[3 /* mffdgsr */] <-5.5219616E-9f ? 
                    -0.09646581f : 
                    -0.09337051f)) : 
             (data[1 /* mffdbvp */] <-1.2825744E-4f ? 
                -0.1040584f : 
                 (data[0 /* mbvp */] <6701.3643f ? 
                    0.109015845f : 
                    -0.025772953f))));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_7_class_7 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <8.124538E-5f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6697.8833f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.77842E-9f ? 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-2.2144317E-9f ? 
                    -0.054312337f : 
                    0.15068167f) : 
                -0.09646099f) : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.61091745f ? 
                 (data[3 /* mffdgsr */] <6.6116095E-9f ? 
                    -0.10216683f : 
                    -0.094919235f) : 
                0.015792012f)) : 
         (data[1 /* mffdbvp */] <1.5809105E-4f ? 
            0.13742958f : 
             (data[2 /* mgsr */] <0.48736507f ? 
                0.04419304f : 
                -0.043638248f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}


class GBMModel_Forest_8 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_8_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_8_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_8_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_8_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_8_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_8_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_8_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_8_class_7.score0(fdata);
  }
}
class GBMModel_Tree_8_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6211232f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6709.9126f ? 
             (data[2 /* mgsr */] <0.44726822f ? 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.39435524f ? 
                     (data[3 /* mffdgsr */] <-6.7035005E-10f ? 
                        -0.0934701f : 
                        -0.09262246f) : 
                    0.03633804f) : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.3574f ? 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6695.969f ? 
                        -0.0932839f : 
                        -0.0944215f) : 
                    -0.098309636f)) : 
            0.04363476f) : 
         (data[3 /* mffdgsr */] <1.0119898E-9f ? 
            0.11979035f : 
            0.0060471715f));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_8_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[1 /* mffdbvp */] <-5.223532E-5f ? 
         (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <-1.0636172E-4f ? 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.1343f ? 
                0.056586653f : 
                -0.096660994f) : 
            0.11482045f) : 
         (data[1 /* mffdbvp */] <3.781132E-5f ? 
             (data[3 /* mffdgsr */] <4.2579917E-9f ? 
                -0.10236534f : 
                -0.096036166f) : 
             (data[1 /* mffdbvp */] <1.2552348E-4f ? 
                0.09611654f : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6703.0337f ? 
                    -0.10155929f : 
                    0.05650392f))));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_8_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.0233304E-9f ? 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5484457f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.4676826E-9f ? 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-1.1263901E-9f ? 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6695.9487f ? 
                        -0.09263676f : 
                        -0.09336054f) : 
                    -0.09242713f) : 
                -0.10575865f) : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.693933E-9f ? 
                -0.092823684f : 
                0.07003183f)) : 
         (data[3 /* mffdgsr */] <1.0119698E-8f ? 
            0.10959403f : 
             (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <2.0694475E-5f ? 
                 (data[3 /* mffdgsr */] <1.5688482E-8f ? 
                    0.11128992f : 
                    0.003935608f) : 
                -0.036617666f)));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_8_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (data[2 /* mgsr */] <0.21629383f ? 
            -0.09695458f : 
             (data[3 /* mffdgsr */] <-3.3212861E-9f ? 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-8.8246965E-9f ? 
                    0.0749417f : 
                    -0.10581177f) : 
                 (data[2 /* mgsr */] <0.4348344f ? 
                    0.13640323f : 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <5.192712E-9f ? 
                        0.0946361f : 
                        -0.029510595f)))) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.9277037E-8f ? 
             (data[0 /* mbvp */] <6696.3906f ? 
                -0.092438504f : 
                 (data[3 /* mffdgsr */] <1.2914024E-8f ? 
                    -0.09322095f : 
                    -0.09388121f)) : 
            -0.09158069f));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_8_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (data[2 /* mgsr */] <0.29855862f ? 
             (data[2 /* mgsr */] <0.18687367f ? 
                -0.09738171f : 
                -0.1013385f) : 
             (data[2 /* mgsr */] <0.38293272f ? 
                0.18248016f : 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <2.8898023E-4f ? 
                     (data[1 /* mffdbvp */] <-1.6311933E-4f ? 
                        0.0020441932f : 
                        -0.096120164f) : 
                    0.033954635f))) : 
        0.07802861f);
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_8_class_5 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.2047475E-9f ? 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <2.5375182E-9f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-3.3416334E-9f ? 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <-1.696155E-6f ? 
                    -0.014938076f : 
                    0.11030041f) : 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <6.0893562E-5f ? 
                    -0.10264432f : 
                    -0.010155106f)) : 
            0.12087746f) : 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.55030125f ? 
             (data[3 /* mffdgsr */] <1.2321919E-8f ? 
                -0.099816956f : 
                -0.09529225f) : 
             (data[2 /* mgsr */] <0.6156954f ? 
                0.061617773f : 
                -0.09670928f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_8_class_6 {
  static final double score0(double[] data) {
    double pred =      (data[1 /* mffdbvp */] <-1.7334032E-4f ? 
         (data[0 /* mbvp */] <6698.8706f ? 
            -0.105404474f : 
            -0.095481515f) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.2899237E-8f ? 
             (data[2 /* mgsr */] <0.26577643f ? 
                0.123545066f : 
                 (data[1 /* mffdbvp */] <-9.017256E-6f ? 
                     (data[3 /* mffdgsr */] <-4.182566E-9f ? 
                        0.12156055f : 
                        -0.0955215f) : 
                     (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.59644383f ? 
                        -0.09720018f : 
                        -0.093782395f))) : 
             (data[3 /* mffdgsr */] <1.7487082E-8f ? 
                0.1327293f : 
                -0.031974595f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_8_class_7 {
  static final double score0(double[] data) {
    double pred =      (data[3 /* mffdgsr */] <-5.465492E-9f ? 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.57813525f ? 
            -0.09535482f : 
            -0.0941171f) : 
         (data[3 /* mffdgsr */] <2.9871888E-10f ? 
            0.08309315f : 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6703.6284f ? 
                 (data[1 /* mffdbvp */] <-1.3937727E-4f ? 
                    0.059316073f : 
                     (data[3 /* mffdgsr */] <6.6605375E-9f ? 
                        -0.10703006f : 
                        -0.062369283f)) : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5960924f ? 
                    -0.021302434f : 
                    0.14652444f))));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}


class GBMModel_Forest_9 {
  public static void score0(double[] fdata, double[] preds) {
    preds[1] += GBMModel_Tree_9_class_0.score0(fdata);
    preds[2] += GBMModel_Tree_9_class_1.score0(fdata);
    preds[3] += GBMModel_Tree_9_class_2.score0(fdata);
    preds[4] += GBMModel_Tree_9_class_3.score0(fdata);
    preds[5] += GBMModel_Tree_9_class_4.score0(fdata);
    preds[6] += GBMModel_Tree_9_class_5.score0(fdata);
    preds[7] += GBMModel_Tree_9_class_6.score0(fdata);
    preds[8] += GBMModel_Tree_9_class_7.score0(fdata);
  }
}
class GBMModel_Tree_9_class_0 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0]) || data[0 /* mbvp */] <6701.6533f ? 
         (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <1.7936695E-4f ? 
             (data[0 /* mbvp */] <6694.111f ? 
                 (data[1 /* mffdbvp */] <-3.6614016E-5f ? 
                    -0.0025889196f : 
                    -0.09855799f) : 
                 (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.58653295f ? 
                     (data[2 /* mgsr */] <0.3700727f ? 
                        -0.091675915f : 
                        -0.09328167f) : 
                    -0.10726333f)) : 
            0.07166749f) : 
         (data[2 /* mgsr */] <0.44082105f ? 
            -0.101606436f : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.0474041E-8f ? 
                0.042869814f : 
                0.1682336f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_9_class_1 {
  static final double score0(double[] data) {
    double pred =      (data[3 /* mffdgsr */] <-9.16691E-9f ? 
        -0.09937274f : 
         (data[3 /* mffdgsr */] <1.0229732E-9f ? 
             (data[2 /* mgsr */] <0.36968985f ? 
                0.13712655f : 
                0.013530838f) : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.6925637f ? 
                 (data[3 /* mffdgsr */] <4.663211E-9f ? 
                    -0.10628355f : 
                     (Double.isNaN(data[0]) || data[0 /* mbvp */] <6700.397f ? 
                        0.012796929f : 
                        -0.09586014f)) : 
                0.13984644f)));
    return pred;
  } // constant pool size = 26B, number of visited nodes = 6, static init size = 0B
}

class GBMModel_Tree_9_class_2 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.0233304E-9f ? 
         (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5484457f ? 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <3.4676826E-9f ? 
                 (data[0 /* mbvp */] <6693.215f ? 
                    -0.09194829f : 
                     (data[2 /* mgsr */] <0.21454808f ? 
                        -0.092036225f : 
                        -0.092807695f)) : 
                -0.10440564f) : 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6702.3716f ? 
                0.059972312f : 
                -0.10005411f)) : 
         (data[3 /* mffdgsr */] <1.0119698E-8f ? 
            0.09291806f : 
             (data[2 /* mgsr */] <0.45237562f ? 
                0.069899954f : 
                 (data[2 /* mgsr */] <0.58432275f ? 
                    -0.0698502f : 
                    0.048477616f))));
    return pred;
  } // constant pool size = 38B, number of visited nodes = 9, static init size = 0B
}

class GBMModel_Tree_9_class_3 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <8.450417E-9f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6706.322f ? 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.4661809f ? 
                 (data[0 /* mbvp */] <6694.857f ? 
                    -0.03789947f : 
                    0.041946083f) : 
                 (data[1 /* mffdbvp */] <-4.5011955E-5f ? 
                    0.0043694586f : 
                    0.097646296f)) : 
            -0.09712838f) : 
         (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.9277037E-8f ? 
             (data[0 /* mbvp */] <6696.3906f ? 
                -0.09198603f : 
                 (data[3 /* mffdgsr */] <1.2914024E-8f ? 
                    -0.09263574f : 
                    -0.093237855f)) : 
            -0.09112851f));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}

class GBMModel_Tree_9_class_4 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.8736088E-8f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6703.988f ? 
             (data[2 /* mgsr */] <0.37587517f ? 
                 (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <1.5612977E-5f ? 
                    0.0645779f : 
                    -0.09606065f) : 
                 (Double.isNaN(data[0]) || data[0 /* mbvp */] <6697.1025f ? 
                     (data[3 /* mffdgsr */] <-3.5090413E-9f ? 
                        -0.093612455f : 
                        -0.09257622f) : 
                    -0.09422149f)) : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.56762016f ? 
                0.07557191f : 
                -0.097577564f)) : 
        0.068018295f);
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_9_class_5 {
  static final double score0(double[] data) {
    double pred =      (data[1 /* mffdbvp */] <-2.6969393E-4f ? 
        0.06736372f : 
         (data[3 /* mffdgsr */] <-1.0519352E-8f ? 
            0.08354754f : 
             (data[2 /* mgsr */] <0.45381024f ? 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <7.4358533E-9f ? 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <-4.8483834E-10f ? 
                        -0.004314198f : 
                        0.1267805f) : 
                    -0.09531372f) : 
                 (data[0 /* mbvp */] <6691.779f ? 
                    0.0067584934f : 
                     (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.30875675E-8f ? 
                        -0.09692108f : 
                        -0.09370296f)))));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_9_class_6 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[0]) || data[0 /* mbvp */] <6703.0f ? 
         (data[1 /* mffdbvp */] <-1.7245635E-4f ? 
            -0.101639375f : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <1.2507803E-8f ? 
                 (data[2 /* mgsr */] <0.3163414f ? 
                    0.11304436f : 
                     (data[3 /* mffdgsr */] <-5.497263E-9f ? 
                        0.06746774f : 
                        -0.09505522f)) : 
                0.09516909f)) : 
         (data[2 /* mgsr */] <0.47545886f ? 
            -0.098431505f : 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.61458516f ? 
                -0.09449591f : 
                -0.09167322f)));
    return pred;
  } // constant pool size = 30B, number of visited nodes = 7, static init size = 0B
}

class GBMModel_Tree_9_class_7 {
  static final double score0(double[] data) {
    double pred =      (Double.isNaN(data[1]) || data[1 /* mffdbvp */] <8.124538E-5f ? 
         (Double.isNaN(data[0]) || data[0 /* mbvp */] <6697.8833f ? 
             (Double.isNaN(data[2]) || data[2 /* mgsr */] <0.5292712f ? 
                 (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <6.77842E-9f ? 
                    0.08627126f : 
                    -0.09694695f) : 
                -0.09735601f) : 
             (Double.isNaN(data[0]) || data[0 /* mbvp */] <6708.8003f ? 
                 (data[3 /* mffdgsr */] <6.6116095E-9f ? 
                    -0.10132522f : 
                    -0.09419219f) : 
                0.014257899f)) : 
         (data[1 /* mffdbvp */] <1.5809105E-4f ? 
            0.11191102f : 
             (Double.isNaN(data[3]) || data[3 /* mffdgsr */] <2.185975E-9f ? 
                -0.039733283f : 
                0.049510963f)));
    return pred;
  } // constant pool size = 34B, number of visited nodes = 8, static init size = 0B
}



